import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Footer } from '../components/Footer';
import { Main } from '../components/Main';
import { Header } from '../components/Header';
import { useCallback, useEffect, useState } from 'react';

export default function Home() {
  const [count, setCount] = useState(1);
  const handleClick = useCallback(
    () => {
      if (count < 10) {
        setCount((prevState) => prevState + 1);
      }
    },
    [count]
  );

  useEffect(() => {
    console.log('マウント時');
    document.body.style.backgroundColor = 'lightblue';
    return () => {
      console.log('アンマウント時');
      document.body.style.backgroundColor = '';
    };
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />
      <h1>{count}</h1>
      <button onClick={handleClick}>ボタン</button>

      <Main page="index" />

      <Footer />
    </div>
  );
}
