import Head from 'next/head';
import { Header } from 'src/components/Header';
import { UsersComponent } from 'src/components/Users';

const Users = () => {
  return (
    <>
      <Head>
        <title>Posts Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      <UsersComponent />
    </>
  );
};

export default Users;
