import Head from 'next/head';
import { CommentsComponent } from 'src/components/Comments';
import { Header } from 'src/components/Header'

const Comments = () => {
  return (
    <>
      <Head>
        <title>Posts Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      <CommentsComponent />
    </>
  );
};

export default Comments;
